"""
Django settings for celjewelry project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

ALLOWED_HOSTS = ["localhost"]

MEDIA_URL = "/media/"
# Application definition

INSTALLED_APPS = [
    'culet.apps.CuletConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "culet.middleware.RequirePasswordChangeMiddleware",
    "culet.middleware.CuletExceptionLoggingMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": (
                "{levelname} {asctime} "
                "{name} {module} "
                "{message}"
            ),
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "culet": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

ROOT_URLCONF = 'celjewelry.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'culet.context_processors.clock_status',
                'culet.context_processors.culet_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'celjewelry.wsgi.application'


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG") == "True"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    },
}

# Only add the legacy MySQL database when its environment variables exist.
# This keeps it available locally without requiring it on DigitalOcean.
if env("OLD_DB_NAME", default=None):
    DATABASES["old_culet"] = {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("OLD_DB_NAME"),
        "USER": env("OLD_DB_USER", default="root"),
        "PASSWORD": env("OLD_DB_PASSWORD", default=""),
        "HOST": env("OLD_DB_HOST", default="127.0.0.1"),
        "PORT": env("OLD_DB_PORT", default="3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 4,
        },
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    # User-uploaded files: style photos, drawings, and spec sheets
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": env("DO_SPACES_ACCESS_KEY"),
            "secret_key": env("DO_SPACES_SECRET_KEY"),
            "bucket_name": env("DO_SPACES_BUCKET_NAME"),
            "region_name": env("DO_SPACES_REGION"),
            "endpoint_url": env("DO_SPACES_ENDPOINT_URL"),

            # Keep uploaded files private and use temporary signed URLs.
            "default_acl": None,
            "querystring_auth": True,
            "querystring_expire": 3600,

            # Prevent a new upload from silently replacing an existing file.
            "file_overwrite": False,

            # Cache files in the user's browser for one day.
            "object_parameters": {
                "CacheControl": "max-age=86400",
            },
        },
    },

    # CSS and JavaScript continue to use WhiteNoise.
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "culet:home"
LOGOUT_REDIRECT_URL = '/accounts/login'
LOGIN_URL = '/accounts/login'