# Generated by Django 4.2.16 on 2024-11-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('PD', 'Production'), ('MR', 'Manager'), ('OF', 'Office')], default='PD', max_length=2),
        ),
    ]
