# Generated by Django 4.2.16 on 2024-11-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_num',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='product',
            field=models.CharField(choices=[('RG', 'Ring'), ('BR', 'Bracelet'), ('NK', 'Necklace')], default='RG', max_length=2),
        ),
    ]
