# Generated by Django 5.1.1 on 2024-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0002_remove_job_job_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='00001', max_length=80),
            preserve_default=False,
        ),
    ]
