# Generated by Django 5.1.1 on 2024-10-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0004_rename_customer_name_job_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='style',
            field=models.CharField(choices=[('RG', 'Ring'), ('BR', 'Bracelet'), ('NK', 'Necklace')], default='RG', max_length=2),
        ),
    ]
