# Generated by Django 5.1.1 on 2024-10-23 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0006_job_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='due',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
