# Generated by Django 4.2.16 on 2025-03-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0006_alter_job_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Stone', max_length=80, unique=True)),
            ],
        ),
    ]
