# Generated by Django 5.1.1 on 2024-10-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0007_job_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
