# Generated by Django 4.2.16 on 2025-04-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0009_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
