# Generated by Django 5.1.1 on 2024-11-08 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0009_job_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('product', models.CharField(choices=[('RG', 'Ring'), ('BR', 'Bracelet'), ('NK', 'Necklace')], default='RG', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culet.style'),
        ),
    ]
