# Generated by Django 4.2.16 on 2024-11-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0010_style_alter_job_created_alter_job_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='product',
            field=models.CharField(choices=[('RG', 'Ring'), ('BR', 'Bracelet'), ('NK', 'Necklace')], max_length=2),
        ),
    ]
