# Generated by Django 4.2.16 on 2025-04-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0010_alter_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='culet.employee'),
            preserve_default=False,
        ),
    ]
