# Generated by Django 4.2.16 on 2024-11-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0011_alter_style_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='product',
            field=models.CharField(choices=[('RG', 'Ring'), ('BR', 'Bracelet'), ('NK', 'Necklace')], default='RG', max_length=2),
        ),
    ]
