# Generated by Django 4.2.16 on 2025-04-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0011_activity_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Employee',
            new_name='employee',
        ),
    ]
