# Generated by Django 4.2.16 on 2025-04-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0012_rename_employee_activity_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
