# Generated by Django 4.2.16 on 2025-04-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0014_timeclock'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='clocked_in',
            field=models.BooleanField(default=False),
        ),
    ]
