# Generated by Django 4.2.16 on 2024-11-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0014_job_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='culet.job'),
        ),
    ]
