# Generated by Django 4.2.16 on 2025-04-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0015_employee_clocked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeclock',
            name='clock_out',
            field=models.DateTimeField(null=True),
        ),
    ]
