# Generated by Django 4.2.16 on 2024-11-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0015_alter_activity_end_alter_activity_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
