# Generated by Django 4.2.16 on 2025-04-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0016_alter_timeclock_clock_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
