# Generated by Django 4.2.16 on 2025-04-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0018_job_location_alter_job_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='in_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(default='', null=True),
        ),
    ]
