# Generated by Django 5.2.1 on 2025-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0019_job_in_work_alter_job_active_alter_job_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_ref_num',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
