# Generated by Django 5.2.1 on 2025-11-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0020_job_customer_ref_num_job_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componenttype',
            name='name',
        ),
        migrations.AddField(
            model_name='component',
            name='component_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='types',
            field=models.CharField(choices=[('ST', 'stone'), ('CS', 'casting'), ('CH', 'chain'), ('OT', 'other')], default='OT', max_length=2),
        ),
    ]
