# Generated by Django 5.2.1 on 2026-02-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0021_remove_componenttype_name_component_component_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('qty_in_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FindingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('unit', models.CharField(default='pcs', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_num', models.IntegerField(blank=True, unique=True)),
                ('weight', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MetalLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_num', models.CharField(max_length=50, unique=True)),
                ('qty_on_hand', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetalPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_num', models.IntegerField(unique=True)),
                ('size', models.CharField(blank=True, default='')),
                ('weight', models.PositiveIntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_req', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('origin_id', models.CharField(blank=True, null=True)),
                ('metal_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='culet.metaltype')),
            ],
        ),
        migrations.CreateModel(
            name='StyleStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_req', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='component',
            name='comp_type',
        ),
        migrations.RemoveField(
            model_name='component',
            name='job',
        ),
        migrations.DeleteModel(
            name='ProductChoices',
        ),
        migrations.AddField(
            model_name='style',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.customer'),
        ),
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='stamp',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.customer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.style'),
        ),
        migrations.AlterField(
            model_name='style',
            name='product',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='findingstock',
            name='finding_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culet.findingtype'),
        ),
        migrations.AddField(
            model_name='metal',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='culet.job'),
        ),
        migrations.AddField(
            model_name='metallot',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.metalpart'),
        ),
        migrations.AddField(
            model_name='metalpart',
            name='metal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.metaltype'),
        ),
        migrations.AddField(
            model_name='metal',
            name='metal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.metaltype'),
        ),
        migrations.AddField(
            model_name='stone',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='culet.job'),
        ),
        migrations.AddField(
            model_name='stone',
            name='stone_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.stonetype'),
        ),
        migrations.AddField(
            model_name='stylemetal',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culet.style'),
        ),
        migrations.AddField(
            model_name='stylestone',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culet.style'),
        ),
        migrations.DeleteModel(
            name='ComponentType',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
    ]
