# Generated by Django 5.2.1 on 2026-02-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0022_findingstock_findingtype_metal_metallot_metalpart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylemetal',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='culet.metalpart'),
            preserve_default=False,
        ),
    ]
