# Generated by Django 5.2.1 on 2026-02-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0023_stylemetal_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metalpart',
            name='metal_type',
        ),
        migrations.RemoveField(
            model_name='stylemetal',
            name='origin_id',
        ),
    ]
