# Generated by Django 5.2.1 on 2026-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0024_remove_metalpart_metal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylemetal',
            name='qty_req',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stylemetal',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
