# Generated by Django 5.2.1 on 2026-02-20 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0025_alter_stylemetal_qty_req_alter_stylemetal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylestone',
            name='stone_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stylestone',
            name='stone_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='culet.stonetype'),
        ),
        migrations.AlterField(
            model_name='metal',
            name='weight',
            field=models.CharField(max_length=10),
        ),
    ]
