# Generated by Django 5.2.1 on 2026-02-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0026_stylestone_stone_size_stylestone_stone_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='stylestone',
            name='stone_shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='culet.stoneshape'),
        ),
    ]
