# Generated by Django 5.2.1 on 2026-02-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0027_stoneshape_stylestone_stone_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
