# Generated by Django 5.2.1 on 2026-03-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0028_alter_style_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylemetal',
            name='metal_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='culet.metaltype'),
        ),
        migrations.AlterField(
            model_name='stylemetal',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.metalpart'),
        ),
        migrations.AlterField(
            model_name='stylestone',
            name='stone_shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.stoneshape'),
        ),
        migrations.AlterField(
            model_name='stylestone',
            name='stone_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.stonetype'),
        ),
    ]
