# Generated by Django 5.2.1 on 2026-03-11 01:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0029_alter_stylemetal_metal_type_alter_stylemetal_part_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetalReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_lot', models.CharField(max_length=250)),
                ('qty_received', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='metallot',
            old_name='lot_num',
            new_name='vendor_lot',
        ),
        migrations.AddConstraint(
            model_name='metallot',
            constraint=models.UniqueConstraint(fields=('part', 'vendor_lot'), name='uniq_vendor_lot_part'),
        ),
        migrations.AddField(
            model_name='metalreceipt',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metalreceiptline',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.metalpart'),
        ),
        migrations.AddField(
            model_name='metalreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='culet.metalreceipt'),
        ),
        migrations.AddConstraint(
            model_name='metalreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'part', 'vendor_lot'), name='unique_receipt_line_per_lot'),
        ),
    ]
