# Generated by Django 5.2.1 on 2026-03-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0030_metalreceipt_metalreceiptline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalreceiptline',
            name='metal_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.metallot'),
        ),
    ]
