# Generated by Django 5.2.1 on 2026-03-12 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0032_metalvendorlot_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalreceipt',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.vendor'),
        ),
        migrations.AlterField(
            model_name='metalvendorlot',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.vendor'),
        ),
    ]
