# Generated by Django 5.2.1 on 2026-03-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0033_alter_metalreceipt_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metallot',
            name='weight_on_hand',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='metalreceiptline',
            name='weight_received',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='metallot',
            name='qty_on_hand',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='metalreceiptline',
            name='qty_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
