# Generated by Django 5.2.1 on 2026-03-23 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0034_metallot_weight_on_hand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_req', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_req', models.PositiveIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_metals', to='culet.job')),
                ('metal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.metaltype')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.metalpart')),
            ],
        ),
        migrations.CreateModel(
            name='JobMetalLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_used', models.PositiveIntegerField(default=0)),
                ('weight_used', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('job_metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_assignments', to='culet.jobmetal')),
                ('metal_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.metallot')),
            ],
        ),
        migrations.CreateModel(
            name='JobStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_size', models.CharField(blank=True, max_length=10, null=True)),
                ('qty_req', models.PositiveIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_stones', to='culet.job')),
                ('stone_shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.stoneshape')),
                ('stone_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.stonetype')),
            ],
        ),
    ]
