# Generated by Django 5.2.1 on 2026-04-08 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0036_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weight',
            new_name='JobWeight',
        ),
    ]
