# Generated by Django 5.2.1 on 2026-05-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0037_rename_weight_jobweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
