# Generated by Django 5.2.1 on 2026-05-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0039_step_jobweight_weight_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobweight',
            old_name='weight_step',
            new_name='step',
        ),
    ]
