# Generated by Django 5.2.1 on 2026-05-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0041_department_active_employee_department_fk_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='activity_steps', to='culet.department')),
            ],
        ),
    ]
