# Generated by Django 5.2.1 on 2026-05-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0042_activitystep'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='culet.activitystep'),
        ),
    ]
