# Generated by Django 5.2.1 on 2026-05-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0043_activity_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
