# Generated by Django 5.2.1 on 2026-05-11 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culet", "0046_jobstatus_location_job_holder_alter_job_assigned_to_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS culet_job_location_id_ee186efd RENAME TO culet_job_holder_id_ee186efd;",
            reverse_sql="ALTER INDEX IF EXISTS culet_job_holder_id_ee186efd RENAME TO culet_job_location_id_ee186efd;",
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="culet.location",
            ),
        ),
    ]