# Generated by Django 5.2.1 on 2026-05-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0047_add_missing_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
