# Generated by Django 5.2.1 on 2026-05-13 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0048_remove_role_department_alter_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='findingstock',
            old_name='qty_in_stock',
            new_name='qty_on_hand',
        ),
        migrations.AddField(
            model_name='findingstock',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='findingstock',
            name='metal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.metaltype'),
        ),
        migrations.AddField(
            model_name='findingstock',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='findingstock',
            name='finding_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.findingtype'),
        ),
        migrations.AlterField(
            model_name='findingstock',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name='JobFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_req', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('qty_used', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.findingstock')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_findings', to='culet.job')),
            ],
        ),
        migrations.CreateModel(
            name='StyleFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_req', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.findingstock')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_findings', to='culet.style')),
            ],
        ),
    ]
