# Generated by Django 5.2.1 on 2026-05-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0049_rename_qty_in_stock_findingstock_qty_on_hand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='due',
            field=models.DateField(),
        ),
    ]
