# Generated by Django 5.2.1 on 2026-05-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0050_alter_job_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_num',
            new_name='barcode',
        ),
    ]
