# Generated by Django 5.2.1 on 2026-05-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0051_rename_job_num_job_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='customer_ref_num',
            new_name='stock_num',
        ),
    ]
