# Generated by Django 5.2.1 on 2026-05-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0052_rename_customer_ref_num_job_stock_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_receive_all',
            field=models.BooleanField(default=False),
        ),
    ]
