# Generated by Django 5.2.1 on 2026-05-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0053_role_can_receive_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='can_receive_all',
            new_name='can_receive_all_jobs',
        ),
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
