# Generated by Django 5.2.1 on 2026-06-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0054_rename_can_receive_all_role_can_receive_all_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metallot',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='jobweight',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Piece Weight'),
        ),
    ]
