# Generated by Django 5.2.1 on 2026-06-18 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0055_metallot_cost_alter_jobweight_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='culet.job')),
                ('shipped_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_shipments', to='culet.employee')),
            ],
            options={
                'ordering': ['-shipped_at'],
            },
        ),
    ]
