# Generated by Django 5.2.1 on 2026-06-19 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0056_jobship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='stock_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobship',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='culet.job'),
        ),
        migrations.CreateModel(
            name='JobTransferMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('memo_to', models.CharField(blank=True, help_text='Optional customer, building, department, or recipient name', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfer_memos', to='culet.employee')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_memos_from', to='culet.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_memos_to', to='culet.location')),
            ],
        ),
        migrations.CreateModel(
            name='JobTransferMemoLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines_from', to='culet.location')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_memo_lines', to='culet.job')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='culet.jobtransfermemo')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines_to', to='culet.location')),
            ],
            options={
                'unique_together': {('memo', 'job')},
            },
        ),
    ]
