# Generated by Django 5.2.1 on 2026-06-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0057_alter_job_stock_num_alter_jobship_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalreceiptline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
