# Generated by Django 5.2.1 on 2026-06-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0058_metalreceiptline_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalreceiptline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
