# Generated by Django 5.2.1 on 2026-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0059_alter_metalreceiptline_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
