# Generated by Django 5.2.1 on 2026-06-29 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0060_activity_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_piecework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='piecework_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PieceworkMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piecework_memos_assigned', to='culet.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piecework_memos_created', to='culet.employee')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='culet.location')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piecework_memos_returned', to='culet.employee')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='culet.location')),
            ],
        ),
        migrations.CreateModel(
            name='PieceworkMemoLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culet.job')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='culet.pieceworkmemo')),
            ],
        ),
    ]
