# Generated by Django 5.2.1 on 2026-06-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0061_job_is_piecework_job_piecework_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtransfermemo',
            name='memo_num',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='pieceworkmemo',
            name='memo_num',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
