# Generated by Django 5.2.1 on 2026-06-29 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0062_jobtransfermemo_memo_num_pieceworkmemo_memo_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('pass', 'Passed'), ('fail', 'Failed')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspections', to='culet.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='culet.job')),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspectionFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('failure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_failures', to='culet.failuretype')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='culet.qualityinspection')),
            ],
            options={
                'ordering': ['failure_type__sort_order', 'failure_type__name'],
            },
        ),
    ]
