# Generated by Django 5.2.1 on 2026-07-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0065_job_repair_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='stock_num',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
