# Generated by Django 5.2.1 on 2026-07-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0067_job_repair_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystep',
            name='code',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
