# Generated by Django 5.2.1 on 2026-07-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0068_activitystep_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='code',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
