# Generated by Django 5.2.1 on 2026-07-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0069_step_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_piecework',
            field=models.BooleanField(default=False),
        ),
    ]
