# Generated by Django 5.2.1 on 2026-07-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0071_remove_employee_department_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_qc',
            field=models.BooleanField(default=False),
        ),
    ]
