# Generated by Django 5.2.1 on 2026-07-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0072_employee_can_qc'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a photograph of the finished style.', null=True, upload_to='styles/photos/'),
        ),
        migrations.AddField(
            model_name='style',
            name='spec_sheet',
            field=models.FileField(blank=True, help_text='Upload the style specification sheet as a PDF.', null=True, upload_to='styles/spec-sheets/'),
        ),
        migrations.AlterField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
