# Generated by Django 5.2.1 on 2026-07-15 22:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('culet', '0073_style_photo_style_spec_sheet_alter_style_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=100)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('git_commit', models.CharField(blank=True, max_length=40)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LegacyRecordMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_table', models.CharField(max_length=100)),
                ('legacy_id', models.BigIntegerField()),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('skipped', 'Skipped')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_maps', to='culet.legacyimportrun')),
            ],
            options={
                'ordering': ['legacy_table', 'legacy_id', 'content_type_id'],
                'indexes': [models.Index(fields=['legacy_table', 'legacy_id'], name='legacy_table_id_idx'), models.Index(fields=['content_type', 'object_id'], name='legacy_target_idx')],
                'constraints': [models.UniqueConstraint(fields=('legacy_table', 'legacy_id', 'content_type'), name='uniq_legacy_record_target_type')],
            },
        ),
    ]
