# Generated by Django 5.2.1 on 2026-07-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0074_legacyimportrun_legacyrecordmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalpart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='culet.customer'),
        ),
        migrations.AlterField(
            model_name='jobmetal',
            name='weight_req',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='metallot',
            name='weight_on_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stone',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stylemetal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
