# Generated by Django 5.2.1 on 2026-07-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0075_metalpart_customer_alter_jobmetal_weight_req_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
