# Generated by Django 5.2.1 on 2026-07-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0077_alter_stylemetal_metal_type_alter_stylemetal_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityinspection',
            name='inspection_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate inspection time in minutes.', null=True, verbose_name='Inspection duration'),
        ),
    ]
