# Generated by Django 5.2.1 on 2026-07-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0079_movementtype_jobmovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmovement',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AddField(
            model_name='movementtype',
            name='job_field',
            field=models.CharField(choices=[('assigned_to', 'Assigned To'), ('holder', 'Holder')], default='holder', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobmovement',
            name='movement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_movements', to='culet.movementtype'),
        ),
        migrations.AlterField(
            model_name='movementtype',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
