# Generated by Django 5.2.1 on 2026-07-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0080_alter_jobmovement_options_movementtype_job_field_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobtransfermemoline',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='jobtransfermemo',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='jobtransfermemo',
            name='memo_to',
        ),
        migrations.RemoveField(
            model_name='jobtransfermemo',
            name='to_location',
        ),
        migrations.AddField(
            model_name='jobtransfermemo',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_transfer_memos', to='culet.employee'),
        ),
        migrations.AddConstraint(
            model_name='jobtransfermemoline',
            constraint=models.UniqueConstraint(fields=('memo', 'job'), name='unique_job_per_transfer_memo'),
        ),
        migrations.RemoveField(
            model_name='jobtransfermemoline',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='jobtransfermemoline',
            name='to_location',
        ),
    ]
