# Generated by Django 5.2.1 on 2026-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0082_employee_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
