# Generated by Django 5.2.1 on 2026-07-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0083_job_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeclock',
            options={'ordering': ['employee__user__last_name', 'employee__user__first_name', 'clock_in']},
        ),
        migrations.AlterField(
            model_name='jobweight',
            name='dust_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobweight',
            name='sprue_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobweight',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Piece Weight'),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeclocks', to='culet.employee'),
        ),
    ]
