# Generated by Django 5.2.1 on 2026-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0084_alter_timeclock_options_alter_jobweight_dust_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_receive_returned_jobs',
            field=models.BooleanField(default=False, help_text='Allow this employee to appear as a destinationwhen jobs are returned.', verbose_name='Can receive returned jobs'),
        ),
    ]
