# Generated by Django 5.2.1 on 2026-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0085_employee_can_receive_returned_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='metal_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
