# Generated by Django 5.2.1 on 2026-08-03 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0087_employee_can_inprocess_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_start_batch',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_batches', to='culet.employee')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_batches', to='culet.activitystep')),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='culet.workbatch'),
        ),
        migrations.AddConstraint(
            model_name='workbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('employee',), name='one_active_work_batch_per_employee'),
        ),
    ]
