# Generated by Django 5.2.1 on 2026-08-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0088_employee_can_start_batch_workbatch_activity_batch_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pieceworkmemoline',
            constraint=models.UniqueConstraint(fields=('memo', 'job'), name='unique_job_per_piecework_memo'),
        ),
    ]
