# Generated by Django 5.2.1 on 2026-08-11 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0090_piecework_line_returns'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspectionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspection', to='culet.activity'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='culet.qualityinspectionstep'),
        ),
    ]
