# Generated by Django 5.2.1 on 2026-09-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0091_qualityinspectionstep_qualityinspection_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceworkmemoline',
            name='activity',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piecework_line', to='culet.activity'),
        ),
    ]
