# Generated by Django 5.2.1 on 2026-09-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0092_piecework_line_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeclock',
            name='adjusted_clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='adjusted_clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
