# Generated by Django 5.2.1 on 2026-09-25 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culet', '0093_timeclock_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceworkmemo',
            name='activity_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piecework_memos', to='culet.activitystep'),
        ),
    ]
