from django.urls import path
from . import views

app_name = "culet"
urlpatterns = [
    path("jobs/", views.JobListView.as_view(), name="index_job"),
    path("jobs/<int:pk>/", views.JobDetailView.as_view(), name="job_detail"),
    path("jobs/<int:pk>/edit/", views.JobUpdateView.as_view(), name="job_update"),
    path("jobs/create", views.JobCreateView.as_view(), name="job_create"),
    path("jobs/<int:pk>/weights/add/", views.JobWeightCreateView.as_view(), name="job_weight_create"),
    path("jobs/weights/lookup/", views.JobWeightLookupView.as_view(), name="job_weight_lookup"),
    path("job-metals/<int:pk>/assign-lots",views.JobMetalLotAssignView.as_view(), name="job_metal_assign_lots"),
    path("htmx/job-style-defaults/", views.JobStyleDefaultsHTMXView.as_view(), name="job_style_defaults_htmx"),
    path("htmx/job-metal/<int:pk>/lots/", views.JobMetalLotAssignmentHTMXView.as_view(), name="job_metal_lot_htmx"),
    path("styles/", views.StyleListView.as_view(), name="index_style"),
    path("styles/create", views.StyleCreateView.as_view(), name="style_create"),
    path("styles/<int:pk>",views.StyleDetailView.as_view(),name="style_detail"),
    path("activities", views.ActivityListView.as_view(),name="activities_index"),
    path("activities/start", views.startWork,name="start_work"),
    path("activities/<int:pk>/stop/<int:job_id>",views.stopWork,name="stop_work"),
    path("jobs/my_jobs/", views.MyJobListView.as_view(), name="my_jobs"),
    path("jobs/assign",views.AssignJobView.as_view(), name="assign_job"),
    path("reporting", views.ReportingListView.as_view(), name="reporting"),
    path("clock_in",views.clock_in,name="clock_in"),
    path("clock_out", views.clock_out,name="clock_out"),
    path("receive", views.receive,name='receive'),
    path("receive_list", views.ReceiveListView.as_view(), name="receive_list"),
    path("inventory/metal/receive/", views.MetalReceiptCreateView.as_view(), name="metal_receipt_create"),
    path("inventory/metal/receipts/", views.MetalReceiptListView.as_view(), name="metal_receipt_list"),
    path("inventory/metal/receipts/<int:pk>/", views.MetalReceiptDetailView.as_view(), name="metal_receipt_detail"),
    path("inventory/metal/vendor-lots/", views.MetalVendorLotListView.as_view(), name="metal_vendor_lot_list"),
    path("inventory/metal/vendor-lots/<int:pk>/", views.MetalVendorLotDetailView.as_view(), name="metal_vendor_lot_detail"),
    path("inventory/metal/lots/", views.MetalLotListView.as_view(), name="metal_lot_list"),
    path("inventory/metal/lots/<int:pk>/", views.MetalLotDetailView.as_view(), name="metal_lot_detail"),
    path("inventory/", views.InventoryDashboardView.as_view(), name="inventory_dashboard"),
    ]
