from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "culet"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("htmx/home-summary/",views.HomeSummaryPartialView.as_view(),name="home_summary_partial",),
    path("jobs/", views.JobListView.as_view(), name="index_job"),
    path("jobs/<int:pk>/", views.JobDetailView.as_view(), name="job_detail"),
    path("jobs/<int:pk>/edit/", views.JobUpdateView.as_view(), name="job_update"),
    path("jobs/create", views.JobCreateView.as_view(), name="job_create"),
    path("jobs/<int:pk>/weights/add/", views.JobWeightCreateView.as_view(), name="job_weight_create"),
    path("jobs/weights/lookup/", views.JobWeightLookupView.as_view(), name="job_weight_lookup"),
    path("job-metals/<int:pk>/assign-lots",views.JobMetalLotAssignView.as_view(), name="job_metal_assign_lots"),
    path("htmx/job-style-defaults/", views.JobStyleDefaultsHTMXView.as_view(), name="job_style_defaults_htmx"),
    path("htmx/job-metal/<int:pk>/lots/", views.JobMetalLotAssignmentHTMXView.as_view(), name="job_metal_lot_htmx"),
    path("styles/", views.StyleListView.as_view(), name="index_style"),
    path("styles/create", views.StyleCreateView.as_view(), name="style_create"),
    path("styles/<int:pk>",views.StyleDetailView.as_view(),name="style_detail"),
    path("activities", views.ActivityListView.as_view(),name="activities_index"),
    path("activities/start", views.startWork,name="start_work"),
    path("activities/<int:pk>/stop/<int:job_id>",views.stopWork,name="stop_work"),
    path("jobs/my_jobs/", views.MyJobListView.as_view(), name="my_jobs"),
    path("jobs/assign",views.AssignJobView.as_view(), name="assign_job"),
    path("jobs/receive-and-assign/",views.ReceiveAndAssignJobsView.as_view(),name="receive_and_assign_jobs",),
    path("jobs/return",views.ReturnJobView.as_view(),name="return_job"),
    path("jobs/ship/",views.BulkJobShipView.as_view(),name="job_ship_bulk"),
    path("reporting", views.ReportingListView.as_view(), name="reporting"),
    path("clock_in",views.clock_in,name="clock_in"),
    path("clock_out", views.clock_out,name="clock_out"),
    path("time-clock/<int:pk>/edit/",views.TimeClockUpdateView.as_view(),name="time_clock_edit"),
    path("receive/", views.ReceiveJobView.as_view(), name="receive"),
    path("receive/all/", views.ReceiveAllJobsView.as_view(), name="receive_all"),
    path("receive_list", views.ReceiveListView.as_view(), name="receive_list"),
    path("inventory/metal/receive/", views.MetalReceiptCreateView.as_view(), name="metal_receipt_create"),
    path("inventory/metal/receipts/", views.MetalReceiptListView.as_view(), name="metal_receipt_list"),
    path("inventory/metal/receipts/<int:pk>/", views.MetalReceiptDetailView.as_view(), name="metal_receipt_detail"),
    path("inventory/metal/vendor-lots/", views.MetalVendorLotListView.as_view(), name="metal_vendor_lot_list"),
    path("inventory/metal/vendor-lots/<int:pk>/", views.MetalVendorLotDetailView.as_view(), name="metal_vendor_lot_detail"),
    path("inventory/metal/", views.MetalInventoryListView.as_view(), name="metal_inventory_list"),
    path("inventory/metal/parts/<int:pk>/", views.MetalPartInventoryDetailView.as_view(), name="metal_part_inventory_detail"),
    path("inventory/metal/lots/<int:pk>/", views.MetalLotDetailView.as_view(), name="metal_lot_detail"),
    path("inventory/", views.InventoryDashboardView.as_view(), name="inventory_dashboard"),

    path("piecework/create/", views.PieceworkCreateView.as_view(), name="piecework_create"),
    path("piecework/open/", views.PieceworkOpenListView.as_view(), name="piecework_open"),
    path("piecework/<int:pk>/print/", views.PieceworkPrintView.as_view(), name="piecework_print"),
    path("piecework/<int:pk>/return/", views.PieceworkReturnView.as_view(), name="piecework_return"),

    #Reports Below This Line
    path("reports/inactive-jobs/", views.InactiveJobsReportView.as_view(), name="report_inactive_jobs"),
    path("reports/weight-loss-by-style/", views.WeightLossByStyleReportView.as_view(), name="report_weight_loss_by_style"),
    path("reports/employee-activity/",views.EmployeeActivityReportView.as_view(),name="report_employee_activity"),
    path("reports/time-clock/",views.TimeClockReportView.as_view(),name="report_time_clock"),
    path("reports/late-jobs/",views.LateJobsReportView.as_view(),name="report_late_jobs"),
    path("reports/clocked-in-idle/", views.ClockedInIdleEmployeesReportView.as_view(), name="report_clocked_in_idle",),
    path("reports/jobs-by-holder/", views.JobsByHolderReportView.as_view(), name="report_jobs_by_holder",),
    path("reports/jobs-shipped/",views.JobShippedReportView.as_view(),name="job_shipped_report",),
    path("reports/style-step-time/",views.StyleStepTimeReportView.as_view(),name="style_step_time_report",),

    #Printing
    path("jobs/envelopes/", views.JobEnvelopePrintFormView.as_view(), name="job_envelope_print_form"),
    path("jobs/envelopes/print/", views.JobEnvelopePrintBatchView.as_view(), name="job_envelope_print_batch"),
    path("jobs/<int:pk>/print-envelope/", views.JobEnvelopePrintView.as_view(), name="job_envelope_print"),
    path("jobs/transfer-memo/",views.JobTransferMemoCreateView.as_view(),name="job_transfer_memo_create"),
    path("jobs/transfer-memo/<int:pk>/print/",views.JobTransferMemoPrintView.as_view(),name="job_transfer_memo_print"),
    path("memos/", views.MemoListView.as_view(), name="memo_list"),
    ]
